language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
install: npm install
before_script:
  - npm install grunt-cli
  - npm install grunt
  - grunt
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
